### PR TITLE
Jballerina

### PR DESCRIPTION
**Pull request by Rajith90**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by Rajith90** [comment]
This is a test comment

**Comment by Rajith90** [comment]
> <https://github.com/Rajith90/product-microgateway/pull/1>
<sub>[View in Slack](https://wso2-apim.slack.com/archives/DLPPFSZUH/p1567060108000700)</sub>

**Comment by praminda** [comment]
Comment

**Comment by praminda** [comment]
Comment 2

**Comment by praminda** [comment]
Comment 3

**Pull request closed without merging**
